[package]
name = "zeroconf-browser-async-example"
version = "0.1.0"
authors = ["Walker Crouse <walkercrouse@hotmail.com>"]
edition = "2018"

[dependencies]
zeroconf = { path = "../../zeroconf" }
tokio = { version = "1.10.1", features = ["full"] }
env_logger = "0.9.0"
